# Generated by Django 3.1 on 2020-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.URLField(default='https://github.com/JaishreeJanu'),
            preserve_default=False,
        ),
    ]
